[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
upload_protocol = teensy-cli
board_microros_distro = jazzy
board_microros_transport = serial
lib_deps = 
	https://github.com/micro-ROS/micro_ros_platformio
  https://github.com/bogde/HX711
build_flags = 
	-Wno-implicit-function-declaration
	-Wno-error=implicit-function-declaration
board_microros_user_meta = colcon.meta
