[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
board_microros_distro = jazzy
board_microros_transport = serial
build_flags = 
    -D_GNU_SOURCE
    -D_POSIX_C_SOURCE=199309L
    -Wno-implicit-function-declaration
    -Wno-error=implicit-function-declaration
lib_deps = 
    https://github.com/micro-ROS/micro_ros_platformio
    bogde/HX711 @ ^0.7.5             
    Wire                            
    paulstoffregen/OneWire @ ^2.3.7
    milesburton/DallasTemperature @ ^4.0.6
    https://github.com/SV-Zanshin/BME680
